### PR TITLE
Applying periodic BCs to parcel mergers

### PR DESCRIPTION
**Pull request by sjboeing**

### CODE REVIEW

**Comment by sjboeing** [comment]
Here is the PR. I have also checked it against my original fix, the results are identical to good precision.

**Comment by matt-frey** [comment]
@sjboeing This looks good, but we also need to fix this in 2D.

**Comment by matt-frey** [comment]
@sjboeing I applied also the changes in the 2D version of your PR. I then cherry-picked the commit and opened a PR to merge into the master branch, see #298.

**Comment by matt-frey** [comment]
@sjboeing If you agree with my commit https://github.com/matt-frey/epic/pull/297/commits/9889e42cd8b9017b29d7ccb3eeaafa52e99558f5, I am happy this to be merged in. Thanks!

**Review by matt-frey — APPROVED** [review]

**Pull request merged**
